super::define_blocks! {
    #[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
    pub enum UnsupportedBlockKind (UnsupportedBlockKindUnit):

    "event_whenthisspriteclicked" => EventWhenthisspriteclicked,
    "event_broadcast" => EventBroadcast,
    "event_broadcastandwait" => EventBroadcastandwait,
    "event_whenbackdropswitchesto" => EventWhenbackdropswitchesto,
    "event_whenbroadcastreceived" => EventWhenbroadcastreceived,
    "event_whengreaterthan" => EventWhengreaterthan,

    "looks_size" => LooksSize,
    "looks_changeeffectby" => LooksChangeeffectby,
    "looks_backdropnumbername" => LooksBackdropnumbername,
    "looks_costume" => LooksCostume,
    "looks_costumenumbername" => LooksCostumenumbername,
    "looks_cleargraphiceffects" => LooksCleargraphiceffects,
    "looks_backdrops" => LooksBackdrops,
    "looks_changesizeby" => LooksChangesizeby,
    "looks_goforwardbackwardlayers" => LooksGoforwardbackwardlayers,
    "looks_gotofrontback" => LooksGotofrontback,
    "looks_hide" => LooksHide,
    "looks_nextbackdrop" => LooksNextbackdrop,
    "looks_nextcostume" => LooksNextcostume,
    "looks_seteffectto" => LooksSeteffectto,
    "looks_setsizeto" => LooksSetsizeto,
    "looks_switchbackdropto" => LooksSwitchbackdropto,
    "looks_switchcostumeto" => LooksSwitchcostumeto,

    "motion_glideto" => MotionGlideto,
    "motion_setrotationstyle" => MotionSetrotationstyle,
    "motion_changexby" => MotionChangexby,
    "motion_changeyby" => MotionChangeyby,
    "motion_setx" => MotionSetx,
    "motion_gotoxy" => MotionGotoxy,
    "motion_goto_menu" => MotionGotoMenu,
    "motion_pointtowards" => MotionPointtowards,
    "motion_direction" => MotionDirection,
    "motion_glidesecstoxy" => MotionGlidesecstoxy,
    "motion_glideto_menu" => MotionGlidetoMenu,
    "motion_goto" => MotionGoto,
    "motion_ifonedgebounce" => MotionIfonedgebounce,
    "motion_movesteps" => MotionMovesteps,
    "motion_pointindirection" => MotionPointindirection,
    "motion_pointtowards_menu" => MotionPointtowardsMenu,
    "motion_sety" => MotionSety,
    "motion_turnleft" => MotionTurnleft,
    "motion_turnright" => MotionTurnright,
    "motion_xposition" => MotionXposition,
    "motion_yposition" => MotionYposition,

    "control_delete_this_clone" => ControlDeleteThisClone,
    "control_create_clone_of" => ControlCreateCloneOf,
    "control_create_clone_of_menu" => ControlCreateCloneOfMenu,
    "control_start_as_clone" => ControlStartAsClone,

    "sound_sounds_menu" => SoundSoundsMenu,
    "sound_volume" => SoundVolume,
    "sound_changeeffectby" => SoundChangeeffectby,
    "sound_changevolumeby" => SoundChangevolumeby,
    "sound_cleareffects" => SoundCleareffects,
    "sound_play" => SoundPlay,
    "sound_playuntildone" => SoundPlayuntildone,
    "sound_seteffectto" => SoundSeteffectto,
    "sound_setvolumeto" => SoundSetvolumeto,
    "sound_stopallsounds" => SoundStopallsounds,

    "sensing_keypressed" => SensingKeypressed,
    "sensing_touchingcolor" => SensingTouchingcolor,
    "sensing_loudness" => SensingLoudness,
    "sensing_coloristouchingcolor" => SensingColoristouchingcolor,
    "sensing_dayssince2000" => SensingDayssince2000,
    "sensing_current" => SensingCurrent,
    "sensing_timer" => SensingTimer,
    "sensing_of" => SensingOf,
    "sensing_of_object_menu" => SensingOfObjectMenu,
    "sensing_keyoptions" => SensingKeyoptions,
    "sensing_mousedown" => SensingMousedown,
    "sensing_mousex" => SensingMousex,
    "sensing_mousey" => SensingMousey,
    "sensing_setdragmode" => SensingSetdragmode,
    "sensing_touchingobject" => SensingTouchingobject,
    "sensing_touchingobjectmenu" => SensingTouchingobjectmenu,
    "sensing_username" => SensingUsername,

    "pen_changePenColorParamBy" => PenChangePenColorParamBy,
    "pen_changePenSizeBy" => PenChangePenSizeBy,
    "pen_clear" => PenClear,
    "pen_menu_colorParam" => PenMenuColorParam,
    "pen_penDown" => PenPenDown,
    "pen_penUp" => PenPenUp,
    "pen_setPenColorParamTo" => PenSetPenColorParamTo,
    "pen_setPenColorToColor" => PenSetPenColorToColor,
    "pen_setPenSizeTo" => PenSetPenSizeTo,
    "pen_stamp" => PenStamp,
}
